name: CD

on:
  push:
    branches: [ master_disabled ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/my-projects/little-notes
            sudo git pull origin master
            sudo docker build -t little-notes:latest .
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker image prune -f
            curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"Bang, berhasil update kode di 'React-LittleNotes',\n\nCommit Message: ${{ github.event.commits[0].message }}\"}" ${{ secrets.DISCORD_WEBHOOK }}
